---
title: "Milestone 5"
author: "Miroslav Bergam"
date: "3/30/2020"
output: bookdown::pdf_document2
bibliography: bibliography.bib
link_citations: true
---

```{r setup, include=FALSE}

statapath <- "/Applications/Stata/Stata.app"
knitr::opts_chunk$set(engine="stata", engine.path=statapath, comment="")

# Importing necessary libaries
library(gtable)
library(stargazer)
library(tidyverse)
library(gt)
library(RStata)
library(Statamarkdown)


```


This is the PDF document of my replication project.

@main_paper @side_paper_1 @side_paper_2 @side_paper_3 @side_paper_4

^[[All analysis for this paper is availible at https://github.com/mirobergam/milestone-5](https://github.com/mirobergam/milestone-5)]

### Overview

### Graphic

```{r}

```

### Appendix

```{r}

import delimited C:\Users\mirobergam\Desktop\DataProjects\Milestone-5\hansen_treul_jop_replication_data.csv
destring geoid2, generate(district)
xtset district congress

xtreg hrcrating laghrcrating population loghrccontrib democrat demvote lgb, re vce(cluster district)
xtreg hrcrating laghrcrating mrp loghrccontrib democrat demvote lgb, re vce(cluster district)
xtreg hrcrating laghrcrating population mrp loghrccontrib democrat demvote lgb, re vce(cluster district)
xtreg hrcrating laghrcrating c.population##c.mrp loghrccontrib democrat demvote lgb, re vce(cluster district)

#Marginal effects of population given district opinion - Figure 1
margins, dydx(population) at(mrp=(10(5)70) democrat=(1)) atmeans
marginsplot, recast(line) recastci(rarea) yline(0)

```

### Bibliography

